spring:
  profiles:
    active: mysql  # Puedes cambiar a mongo según necesites

  main:
    allow-bean-definition-overriding: true

---

spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/comicverse
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Puedes usar "create" si deseas que cree las tablas desde cero
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: mongo

  data:
    mongodb:
      host: localhost
      port: 27017
      database: comicverse

server:
  port: 8080
